### ISSUE TITLE
musi

### ISSUE THREAD

**Issue by Daenyth** [lipu-linku/pali-nimi#21]
#### sona pu

ADJECTIVE artistic, entertaining, frivolous, playful, recreational

#### sona Linku pi toki Inli

artistic, entertaining, frivolous, playful, recreation

#### sona Linku pi toki pona

ijo musi li pana e pilin pona; musi mute la jan li kalama pi wile ala kepeken uta

#### sona ku

entertainment⁵, fun⁵, funny⁵, play⁵, game⁵, comedy⁵, art³, artistic³, fascinating², humour², interesting², irony², sport², enjoy², creative², playoffs²

**Comment by Daenyth** [comment]
I'd like to propose

> entertainment, game, art, amusing, interesting, fun, funny, joking

**Comment by lipamanka** [comment]
conversation starters from @AcipenserSturio: 

> fun / funny should be more prominent, also "play" and "game"

**Comment by Daenyth** [comment]
> fun, game, entertainment, art, amusing, interesting, comical, joking

**Comment by lipamanka** [comment]
it seems a little long and I feel like it's lacking structure, but besides that I like it

**Comment by lipamanka** [comment]
what if we grouped it by english word part of speech and added "play" 
> fun, game, entertainment, art, play, amusing, interesting, comical, joking

**Comment by Daenyth** [comment]
> it seems a little long 

For me it's important to have all those words there because I think that *musi* in particular as a word is especially broader than people are used to in English, which results in learners semi-lexicalizing it to only a subset of its actual semantic zone, IME

> I feel like it's lacking structure, but besides that I like it

Aside from the part of speech grouping, what would you do to improve that?

**Comment by lipamanka** [comment]
hmmm we could add semicolons? I actually don't know.

**Comment by wasokeli** [comment]
more an observation than a suggestion: i feel like "amusement" is a pretty comprehensive single-word definition

**Comment by lipamanka** [comment]
not really. A lot of serious art I don't think counts as amusement. but it covers a LOT of it.

**Comment by AcipenserSturio** [comment]
It might be that "serious unfunny but thoughtprovoking art" is one of those definitions supported by experienced users but not actively being used (either by the general public or by everyone), requiring a usage note. Maybe investigate that usage more?

**Comment by Daenyth** [comment]
I don't really think it requires a note, if we just have "art" as the word in the list. Many pieces of art are musi in multiple aspects

**Comment by AcipenserSturio** [comment]
Coming back from sona-kulupu: about 60% seem to agree serious, non-funny art is musi. I'm okay with that not requiring a usage note

**Comment by AcipenserSturio** [comment]
@lipamanka @Daenyth what do we gain by listing both "comical" and "joking"?

Otherwise I think the proposal is about right

**Comment by lipamanka** [comment]
I think we can lose joking maybe but if @Daenyth can think of a good reason to keep both or lose comical instead I support them in that

**Comment by Daenyth** [comment]
>    fun, game, entertainment, art, play, amusing, interesting, comical

**Comment by gregdan3** [comment]
mi ilo e niiiiii

**Comment by Daenyth** [comment]
kala Asi proposed including "silly"

> fun, game, entertainment, art, play, amusing, interesting, comical, silly

**Comment by gregdan3** [comment]
mi ilo e ni ante
